apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tas-handson-for-dev
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: platform-team
